no_log_directory:
  controllers:
    - controller1:
        arg: value

  logging:
    arg: value


no_logging_section:
  controllers:
    - controller1:
        arg: value

default: &shared
  controllers:
    controller1:
      arg: value
  
  logging:
    directory: 'spec/tmp'
    home: 'spec/tmp/home'
    homes_to_keep: 5
  
  timings:
    worker_loop_interval: 5
    controller_loop_interval: 1
  
  network:
    scheduler: http://example.co.uk
    cert: cert.pem

  datastore:
    filename: /path/to/datastore.db

test:
  <<: *shared

test_daemon_helper_instantiate:
  <<: *shared
  controllers:
    shell:
      arg1: value
      arg2: value2

test_daemon_helper_single_controller:
  <<: *shared
  controllers:
    shell:
      maximum: 5

test_daemon_helper_two_controllers:
  <<: *shared
  controllers:
    test:
      maximum: 5
    shell:
      maximum: 5
